<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="15" total="17" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="testList" duration-ms="143098" started-at="2015-12-29T15:08:38Z" finished-at="2015-12-29T15:11:01Z">
    <groups>
    </groups>
    <test name="myTest" duration-ms="143098" started-at="2015-12-29T15:08:38Z" finished-at="2015-12-29T15:11:01Z">
      <class name="com.perfectomobile.DomExe">
        <test-method status="PASS" signature="BeforeSuite()[pri:0, instance:com.perfectomobile.DomExe@6dbd984]" name="BeforeSuite" is-config="true" duration-ms="15" started-at="2015-12-29T17:08:38Z" finished-at="2015-12-29T17:08:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BeforeSuite -->
        <test-method status="PASS" signature="BeforeSuite()[pri:0, instance:com.perfectomobile.NativeExe@6b4ceb0d]" name="BeforeSuite" is-config="true" duration-ms="1" started-at="2015-12-29T17:08:38Z" finished-at="2015-12-29T17:08:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BeforeSuite -->
        <test-method status="FAIL" signature="testDevices(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.perfectomobile.DomExe@6dbd984]" name="testDevices" duration-ms="24760" started-at="2015-12-29T17:09:57Z" data-provider="Devices" finished-at="2015-12-29T17:10:22Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Android]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[D1EB6319]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[community.perfectomobile.com]]>
              </value>
            </param>
            <param index="3">
              <value is-null="true"/>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Test Ended with error]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Test Ended with error
	at org.testng.Assert.fail(Assert.java:94)
	at com.perfectomobile.DomExe.testDevices(DomExe.java:108)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:75)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDevices -->
        <test-method status="FAIL" signature="testDevices(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.perfectomobile.DomExe@6dbd984]" name="testDevices" duration-ms="27458" started-at="2015-12-29T17:09:57Z" data-provider="Devices" finished-at="2015-12-29T17:10:25Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Android]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[02157DF2CC01C136]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[community.perfectomobile.com]]>
              </value>
            </param>
            <param index="3">
              <value is-null="true"/>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Test Ended with error]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Test Ended with error
	at org.testng.Assert.fail(Assert.java:94)
	at com.perfectomobile.DomExe.testDevices(DomExe.java:108)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:75)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDevices -->
        <test-method status="FAIL" signature="testDevices(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.perfectomobile.DomExe@6dbd984]" name="testDevices" duration-ms="687" started-at="2015-12-29T17:09:57Z" data-provider="Devices" finished-at="2015-12-29T17:09:58Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Android]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[012861923FDC3846]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[community.perfectomobile.com]]>
              </value>
            </param>
            <param index="3">
              <value is-null="true"/>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Test Ended with error]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Test Ended with error
	at org.testng.Assert.fail(Assert.java:94)
	at com.perfectomobile.DomExe.testDevices(DomExe.java:108)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:75)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDevices -->
        <test-method status="FAIL" signature="testDevices(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.perfectomobile.DomExe@6dbd984]" name="testDevices" duration-ms="63979" started-at="2015-12-29T17:09:57Z" data-provider="Devices" finished-at="2015-12-29T17:11:01Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[ios]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[753CE046572094378A8CB5D91BC262613969596F]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[community.perfectomobile.com]]>
              </value>
            </param>
            <param index="3">
              <value is-null="true"/>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Test Ended with error]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Test Ended with error
	at org.testng.Assert.fail(Assert.java:94)
	at com.perfectomobile.DomExe.testDevices(DomExe.java:108)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:75)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDevices -->
        <test-method status="FAIL" signature="testDevices(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.perfectomobile.DomExe@6dbd984]" name="testDevices" duration-ms="23146" started-at="2015-12-29T17:09:57Z" data-provider="Devices" finished-at="2015-12-29T17:10:20Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Android]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[9B99B8B1]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[community.perfectomobile.com]]>
              </value>
            </param>
            <param index="3">
              <value is-null="true"/>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Test Ended with error]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Test Ended with error
	at org.testng.Assert.fail(Assert.java:94)
	at com.perfectomobile.DomExe.testDevices(DomExe.java:108)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:75)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDevices -->
        <test-method status="FAIL" signature="testDevices(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.perfectomobile.DomExe@6dbd984]" name="testDevices" duration-ms="36590" started-at="2015-12-29T17:09:57Z" data-provider="Devices" finished-at="2015-12-29T17:10:34Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[ios]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[EA2D3BF43555096BEAAE3E9AA6DAA57CECB49485]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[community.perfectomobile.com]]>
              </value>
            </param>
            <param index="3">
              <value is-null="true"/>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Test Ended with error]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Test Ended with error
	at org.testng.Assert.fail(Assert.java:94)
	at com.perfectomobile.DomExe.testDevices(DomExe.java:108)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:75)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDevices -->
        <test-method status="FAIL" signature="testDevices(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.perfectomobile.DomExe@6dbd984]" name="testDevices" duration-ms="34277" started-at="2015-12-29T17:09:57Z" data-provider="Devices" finished-at="2015-12-29T17:10:31Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[ios]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[7BF8C558195939D244E20AF8E265DAF59B540E30]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[community.perfectomobile.com]]>
              </value>
            </param>
            <param index="3">
              <value is-null="true"/>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Test Ended with error]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Test Ended with error
	at org.testng.Assert.fail(Assert.java:94)
	at com.perfectomobile.DomExe.testDevices(DomExe.java:108)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:75)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDevices -->
        <test-method status="FAIL" signature="testDevices(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.perfectomobile.DomExe@6dbd984]" name="testDevices" duration-ms="32218" started-at="2015-12-29T17:09:57Z" data-provider="Devices" finished-at="2015-12-29T17:10:29Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Android]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[LGD850961FEC7B]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[community.perfectomobile.com]]>
              </value>
            </param>
            <param index="3">
              <value is-null="true"/>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Test Ended with error]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Test Ended with error
	at org.testng.Assert.fail(Assert.java:94)
	at com.perfectomobile.DomExe.testDevices(DomExe.java:108)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:75)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDevices -->
        <test-method status="PASS" signature="AfterSuite()[pri:0, instance:com.perfectomobile.DomExe@6dbd984]" name="AfterSuite" is-config="true" duration-ms="0" started-at="2015-12-29T17:11:01Z" finished-at="2015-12-29T17:11:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AfterSuite -->
        <test-method status="PASS" signature="AfterSuite()[pri:0, instance:com.perfectomobile.NativeExe@6b4ceb0d]" name="AfterSuite" is-config="true" duration-ms="1" started-at="2015-12-29T17:11:01Z" finished-at="2015-12-29T17:11:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AfterSuite -->
      </class> <!-- com.perfectomobile.DomExe -->
      <class name="com.perfectomobile.BuildDevicesList">
        <test-method status="PASS" signature="deviceList()[pri:0, instance:com.perfectomobile.BuildDevicesList@4ba56ca0]" name="deviceList" duration-ms="2193" started-at="2015-12-29T17:08:38Z" finished-at="2015-12-29T17:08:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deviceList -->
      </class> <!-- com.perfectomobile.BuildDevicesList -->
      <class name="com.perfectomobile.NativeExe">
        <test-method status="FAIL" signature="testDevices(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.perfectomobile.NativeExe@6b4ceb0d]" name="testDevices" duration-ms="63072" started-at="2015-12-29T17:08:40Z" data-provider="Devices" finished-at="2015-12-29T17:09:43Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Android]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[com.bloomfire.android.perfecto]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[D1EB6319]]>
              </value>
            </param>
            <param index="3">
              <value is-null="true"/>
            </param>
            <param index="4">
              <value>
                <![CDATA[PUBLIC:PMcommunity\\Bloomfire-perfecto-release.apk]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Test Ended with error]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Test Ended with error
	at org.testng.Assert.fail(Assert.java:94)
	at com.perfectomobile.NativeExe.testDevices(NativeExe.java:110)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:75)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDevices -->
        <test-method status="PASS" signature="testDevices(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.perfectomobile.NativeExe@6b4ceb0d]" name="testDevices" duration-ms="62727" started-at="2015-12-29T17:08:40Z" data-provider="Devices" finished-at="2015-12-29T17:09:43Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Android]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[com.bloomfire.android.perfecto]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[02157DF2CC01C136]]>
              </value>
            </param>
            <param index="3">
              <value is-null="true"/>
            </param>
            <param index="4">
              <value>
                <![CDATA[PUBLIC:PMcommunity\\Bloomfire-perfecto-release.apk]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDevices -->
        <test-method status="FAIL" signature="testDevices(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.perfectomobile.NativeExe@6b4ceb0d]" name="testDevices" duration-ms="72079" started-at="2015-12-29T17:08:40Z" data-provider="Devices" finished-at="2015-12-29T17:09:52Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[ios]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[com.bloomfire.enterprise.perfecto]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[753CE046572094378A8CB5D91BC262613969596F]]>
              </value>
            </param>
            <param index="3">
              <value is-null="true"/>
            </param>
            <param index="4">
              <value>
                <![CDATA[PUBLIC:PMcommunity\\perfecto-enterprise-2.11(20151117.1).ipa]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Test Ended with error]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Test Ended with error
	at org.testng.Assert.fail(Assert.java:94)
	at com.perfectomobile.NativeExe.testDevices(NativeExe.java:110)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:75)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDevices -->
        <test-method status="FAIL" signature="testDevices(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.perfectomobile.NativeExe@6b4ceb0d]" name="testDevices" duration-ms="1742" started-at="2015-12-29T17:08:40Z" data-provider="Devices" finished-at="2015-12-29T17:08:42Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Android]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[com.bloomfire.android.perfecto]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[012861923FDC3846]]>
              </value>
            </param>
            <param index="3">
              <value is-null="true"/>
            </param>
            <param index="4">
              <value>
                <![CDATA[PUBLIC:PMcommunity\\Bloomfire-perfecto-release.apk]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Test Ended with error]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Test Ended with error
	at org.testng.Assert.fail(Assert.java:94)
	at com.perfectomobile.NativeExe.testDevices(NativeExe.java:110)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:75)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDevices -->
        <test-method status="FAIL" signature="testDevices(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.perfectomobile.NativeExe@6b4ceb0d]" name="testDevices" duration-ms="64074" started-at="2015-12-29T17:08:40Z" data-provider="Devices" finished-at="2015-12-29T17:09:44Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Android]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[com.bloomfire.android.perfecto]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[LGD850961FEC7B]]>
              </value>
            </param>
            <param index="3">
              <value is-null="true"/>
            </param>
            <param index="4">
              <value>
                <![CDATA[PUBLIC:PMcommunity\\Bloomfire-perfecto-release.apk]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Test Ended with error]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Test Ended with error
	at org.testng.Assert.fail(Assert.java:94)
	at com.perfectomobile.NativeExe.testDevices(NativeExe.java:110)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:75)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDevices -->
        <test-method status="FAIL" signature="testDevices(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.perfectomobile.NativeExe@6b4ceb0d]" name="testDevices" duration-ms="76875" started-at="2015-12-29T17:08:40Z" data-provider="Devices" finished-at="2015-12-29T17:09:57Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[ios]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[com.bloomfire.enterprise.perfecto]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[EA2D3BF43555096BEAAE3E9AA6DAA57CECB49485]]>
              </value>
            </param>
            <param index="3">
              <value is-null="true"/>
            </param>
            <param index="4">
              <value>
                <![CDATA[PUBLIC:PMcommunity\\perfecto-enterprise-2.11(20151117.1).ipa]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Test Ended with error]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Test Ended with error
	at org.testng.Assert.fail(Assert.java:94)
	at com.perfectomobile.NativeExe.testDevices(NativeExe.java:110)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:75)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDevices -->
        <test-method status="FAIL" signature="testDevices(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.perfectomobile.NativeExe@6b4ceb0d]" name="testDevices" duration-ms="63317" started-at="2015-12-29T17:08:40Z" data-provider="Devices" finished-at="2015-12-29T17:09:44Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Android]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[com.bloomfire.android.perfecto]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[9B99B8B1]]>
              </value>
            </param>
            <param index="3">
              <value is-null="true"/>
            </param>
            <param index="4">
              <value>
                <![CDATA[PUBLIC:PMcommunity\\Bloomfire-perfecto-release.apk]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Test Ended with error]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Test Ended with error
	at org.testng.Assert.fail(Assert.java:94)
	at com.perfectomobile.NativeExe.testDevices(NativeExe.java:110)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:75)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDevices -->
        <test-method status="FAIL" signature="testDevices(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.perfectomobile.NativeExe@6b4ceb0d]" name="testDevices" duration-ms="44796" started-at="2015-12-29T17:08:40Z" data-provider="Devices" finished-at="2015-12-29T17:09:25Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[ios]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[com.bloomfire.enterprise.perfecto]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[7BF8C558195939D244E20AF8E265DAF59B540E30]]>
              </value>
            </param>
            <param index="3">
              <value is-null="true"/>
            </param>
            <param index="4">
              <value>
                <![CDATA[PUBLIC:PMcommunity\\perfecto-enterprise-2.11(20151117.1).ipa]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Test Ended with error]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Test Ended with error
	at org.testng.Assert.fail(Assert.java:94)
	at com.perfectomobile.NativeExe.testDevices(NativeExe.java:110)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:75)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDevices -->
      </class> <!-- com.perfectomobile.NativeExe -->
    </test> <!-- myTest -->
  </suite> <!-- testList -->
</testng-results>
